config/routes.rb
Omrails::Application.routes.draw do
  
  
  devise_for :users

  root :to => 'static_pages#home'
  get "about" => 'static_pages#about'
  get "faq" => 'static_pages#faq'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
        <center>
          <small>
       <%= link_to "PROJECT", "http://qroom.ru" %>
       by Pavel Gusev
     </small>
   </center>
    </div>
    

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">MY FIRST PROJECT</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">

              <nav>
                <ul class="nav pull-right">
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "FAQ", faq_path %></li>
          <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end%>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omrails</title>
   <%= stylesheet_link_tag    "application", :media => "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
  </head>
  <body>
     <%= render 'layouts/header' %>
      <div class="container">
          

              <% flash.each do |key, value| %>
              <%= content_tag(:div, value, class: "alert alert-#{key}") %>
              <% end %>

          <%= yield %>

              <%= render 'layouts/footer' %>
      </div>

  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>
    <a href="http://omrails.com/">One Month Rails</a>
    is a project to teach 
    <a href="http://rubyonrails.org/">Ruby on Rails</a> 
    in one month. This is the sample application.
</p>

app/views/static_pages/faq.html.erb
<h1>FAQ</h1>
<p>
    <a href="http://omrails.com/">One Month Rails</a>
    is a project to teach 
    <a href="http://rubyonrails.org/">Ruby on Rails</a> 
    in one month. This is the sample application.
</p>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="span2">
  	<h2>span2 column</h2>
  </div>
  
  <div class="span10">

		<% if user_signed_in? %>
		<h1>You're signed in'</h1>

		<% else %>
		<div class="center hero-unit">
		    <h1>Welcome to One Month Rails</h1>

		    <h2>
		      You've found the home page for the
		      <%= link_to "One Month Rails", "http://onemonthrails.com" %>
		      first application.
		    </h2>

		    <%= link_to "Sign up now!", new_user_registration_path, 
		                                class: "btn btn-large btn-primary" %>
		</div>

		<% end%>

  </div>
</div>